name: Deploy MeatApp to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build Expo Web App
      - name: Build Expo Web
        run: npx expo export --platform web

      # Copy dist folder to EC2
      - name: Copy dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/meatapp-dist"

      # Deploy using SSH
      - name: Deploy to NGINX
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            # Remove old frontend
            sudo rm -rf /var/www/html/*

            # Copy new frontend
            sudo cp -r /home/ubuntu/meatapp-dist/dist/* /var/www/html/

            # Restart nginx
            sudo systemctl restart nginx
